### ISSUE TITLE
refreshing the page go to the error page 

### ISSUE THREAD

**Issue by DarkKnight1992** [wlepinski/angularjs-yii-boilerplate#3]
Hi Thanks of creating this awesome boilerplate i know yii2 is the latest version but our website is built on Yii and the main app is inside a different folder and we wanted to bring it to the root folder. Your boiler plate did the fantastic job there but have one issue that when i refresh the page it redirect to the error page instead of the actual route. Is there a work around or fix for this ?

**Comment by wlepinski** [comment]
I think you need to create a "catchall" route to serve the index.

**Comment by DarkKnight1992** [comment]
Thanks wlepinski, that worked like a charm.

**Comment by DarkKnight1992** [comment]
you are awesome sir, Thanks a ton for this boilerplate.
